version: '3.8'

services:
  # --- PostgreSQL with pgvector ---
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mkitsdts
      POSTGRES_PASSWORD: mkitsdts
      POSTGRES_DB: tx_test
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mkitsdts -d tx_test"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # --- Redis ---
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  # --- Jaeger ---
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
      - "6831:6831/udp"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: