grpc:
  address: ":50051"

postgres:
  host: "localhost"
  port: 5432
  user: "mkitsdts"
  password: "mkitsdts"
  dbname: "tx_test"
  sslmode: "disable"

redis:
  address: "localhost:6379"
  password: ""
  db: 0

jaeger:
  endpoint: "http://localhost:14268/api/traces"
  service_name: "tx-service"

pprof:
  address: ":6060"